### ISSUE TITLE
Game terminates on start(PDRPC v0.0.9)

### ISSUE THREAD

**Issue by FurretNoYou** [Braasileiro/PDRPC#2]
After updating the mod to latest version and launching the game with couple other mods it simply crashes before even showing a sega logo. Also asked my friend to check it out on his pc and without any other mods. Same result.
By the way previous version(I dont remember which one exactly didnt work at all but at least game was able to run normally)

**Comment by Braasileiro** [comment]
I'm aware of that issue. I'll rollback the changes.

Sorry for the trouble.
