### ISSUE TITLE
Don't getting the rich presence

### ISSUE THREAD

**Issue by Emer1ne** [Braasileiro/PDRPC#5]
After last time i played the game it's not getting the rich presence, just the default one.
I already tried to launch the game and discord as Administrator but they just can't see each other.
I tried to check a console and there was only a message like:
[PDRPC]: Waiting for DIscord...

**Comment by Emer1ne** [comment]
Okay, i guess the problem is the new version of discord,
another apps with rich presence also doesn't appear

**Comment by Braasileiro** [comment]
I couldn't replicate it here. I'm on the latest stable version of Discord and RPC worked fine.

Are you on Discord Canary?

**Comment by Emer1ne** [comment]
No, i'm using the official client from discord.com

**Comment by Warfutt** [comment]
It happens to me too. I only get "[PDRPC]: Waiting for Discord..." in the console.
I already had Discord running as an administrator and also ran the game as an administrator. I even tried running one first, then the other and viceversa but I still don't get the rich presence.
The interesting thing is that only when I run the game as an administrator, the last message in the console is "[PDRPC]: Internal database loaded." and not "[PDRPC]: Waiting for Discord". I get waiting for discord only when the game is running normally, not as an administrator.
(I installed the mod with Diva Mod Manager via 1-click-install of Gamebanana) (I'm in latest version of Discord 1.0.9006)

**Comment by Braasileiro** [comment]
Sorry for the late response.

Well, here are some things you two can try:

### Clear the Discord cache and reinstall
Close the Discord, open **"Run"** and type **"%AppData%\discord"** and press **"OK"**. Delete all contents in this folder.

**Uninstall the Discord and reinstall.** You will have to log in to Discord again.

### Change the PDRPC mod priority
In DivaModManager, leave PDRPC as the first mod to load. It's also worth testing only with it activated, sometimes some mod may be conflicting.

Although I don't know of any to this day that conflicts with the PDRPC.

### Reinstall the mod
Delete the mod through DivaModManager or manually and check the **"mods"** folder in the game's installation directory to see if there are any remnants left.

After the process, reinstall the mod through GameBanana or download it from GitHub.

### Check the requeriments
The PDRPC needs [.NET Framework 4.8 Runtime](https://dotnet.microsoft.com/en-us/download/dotnet-framework/net48) and [Visual C++ 2015+ x64 Runtime](https://aka.ms/vs/17/release/vc_redist.x64.exe) to work.
If you have Windows 10 updated at least 2019 onwards, the .NET Framework 4.8 Runtime will already be built in.

### Reinstall the DivaModManager and DivaModLoader
Only if nothing above works.

The PDRPC does not necessarily need to be run as Administrator to work. Try to do this with normal permissions if possible. Both on Discord and in-game (Steam).

**Comment by Braasileiro** [comment]
### Update
It appears to be a random internal bug related to the Discord API and is affecting some people randomly as well.
I will follow the situation and give a feeback here in this issue.

**Comment by Braasileiro** [comment]
It's fixed. Just restart Discord for the changes to take effect.

I'm closing this issue. Any problems let me know please.

![Rich Presence issue fixed](https://cdn.discordapp.com/attachments/531653817536872463/1032752930140467331/unknown.png)
